# Generated by Django 5.2 on 2025-04-13 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_student_evaluators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('marks', models.FloatField()),
                ('weightage', models.FloatField()),
                ('pic', models.CharField(max_length=50)),
                ('contents', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grader', models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'examiner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.markingscheme')),
            ],
            options={
                'unique_together': {('student', 'scheme', 'grader')},
            },
        ),
    ]
