# Generated by Django 5.2 on 2025-05-05 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_alter_coursecoordinator_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('marks', models.FloatField()),
                ('weightage', models.FloatField()),
                ('pic', models.JSONField(blank=True, default=list)),
                ('contents', models.JSONField()),
                ('course', models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], default='FYP1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grader', models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'examiner', 'course_coordinator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.markingscheme')),
            ],
            options={
                'unique_together': {('student', 'scheme', 'grader')},
            },
        ),
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], max_length=5)),
                ('total_mark', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_marks', to='users.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
