# Generated by Django 5.2 on 2025-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingscheme',
            name='pic',
            field=models.JSONField(default=list),
        ),
    ]
