# Generated by Django 5.2 on 2025-04-13 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grader',
            field=models.ForeignKey(limit_choices_to={'role__in': ['supervisor', 'examiner', 'course_coordinator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
