# Generated by Django 5.2 on 2025-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_grader'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingscheme',
            name='course',
            field=models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], default='FYP1', max_length=5),
        ),
    ]
