# Generated by Django 5.2 on 2025-05-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_convert_pic_to_jsonb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markingscheme',
            options={'ordering': ['steps']},
        ),
        migrations.AddField(
            model_name='markingscheme',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
