# Generated by Django 5.2 on 2025-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_markingscheme_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingscheme',
            name='pic',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('examiner', 'Examiner'), ('coordinator', 'Coordinator')], max_length=50),
        ),
    ]
