# Generated by Django 5.2 on 2025-05-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_markingscheme_pic'),
        ('users', '0012_alter_coursecoordinator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], max_length=5)),
                ('total_mark', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_marks', to='users.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
