# Generated by Django 5.2 on 2025-05-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_markingscheme_options_markingscheme_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingscheme',
            name='mode',
            field=models.CharField(choices=[('both', 'Both'), ('development', 'Development'), ('research', 'Research')], default='both', max_length=255),
        ),
    ]
