# Generated by Django 5.2 on 2025-05-31 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_markingscheme_mode'),
        ('users', '0018_student_cgpa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('weightage', models.FloatField()),
                ('pic', models.JSONField(default=list)),
                ('course', models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], default='FYP1', max_length=5)),
                ('mode', models.CharField(choices=[('both', 'Both'), ('development', 'Development'), ('research', 'Research')], default='both', max_length=255)),
                ('steps', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['steps'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='totalmarks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='totalmarks',
            name='student',
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('weightage', models.FloatField()),
                ('max_mark', models.FloatField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='grades.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.criteria')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.DeleteModel(
            name='MarkingScheme',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='TotalMarks',
        ),
    ]
