# Generated by Django 5.2 on 2025-05-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_grade_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.grade'),
        ),
    ]
