# Generated by Django 5.2 on 2025-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_studentgrade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='mode',
        ),
        migrations.AddField(
            model_name='criteria',
            name='mode',
            field=models.CharField(choices=[('both', 'Both'), ('development', 'Development'), ('research', 'Research')], default='both', max_length=255),
        ),
    ]
