services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: posse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - DB_NAME=posse_db
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db  # Points to the 'db' service above
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Maps localhost:3000 to Nginx port 80
    depends_on:
      - backend

volumes:
  postgres_data: