# Unique identifier
sonar.projectKey=POSSE-Project
sonar.projectName=POSSE

# Source code locations
sonar.sources=backend,frontend

# Excluded files and directories
sonar.exclusions=**/node_modules/**, **/venv/**, **/*.spec.js, **/*.test.js