databases:
  - name: posseDB
    plan: free
    databaseName: possedb
    user: possedb_user

services:
  - type: web
    plan: free
    name: POSSE
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: posseDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: adminpassword
    postDeployCommand: |
      python manage.py migrate
      python manage.py shell -c "
from django.contrib.auth import get_user_model
import os
User = get_user_model()
User.objects.filter(username=os.environ['DJANGO_SUPERUSER_USERNAME']).delete()
User.objects.create_superuser(
    os.environ['DJANGO_SUPERUSER_USERNAME'],
    os.environ['DJANGO_SUPERUSER_EMAIL'],
    os.environ['DJANGO_SUPERUSER_PASSWORD']
)"
