databases:
  - name: posseDB
    plan: free
    databaseName: possedb
    user: possedb_user

services:
  - type: web
    plan: free
    name: POSSE
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: posseDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
