# Generated by Django 5.2 on 2025-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_documentmodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategories',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentmodes',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
