# Generated by Django 5.2 on 2025-04-20 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_documentcategories_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='submissionStatusTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #FFF or #FFFFFF).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #FFF or #FFFFFF).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
