# Generated by Django 5.2 on 2025-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_systemtheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttheme',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
