# Generated by Django 5.2 on 2025-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_documenttheme_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documentTheme',
        ),
    ]
