# Generated by Django 5.2 on 2025-06-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_delete_documenttheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documentCategories',
        ),
    ]
