# Generated by Django 5.2 on 2025-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Lecture Notes', 'Lecture Notes'), ('Samples', 'Samples'), ('Templates', 'Templates')], max_length=20),
        ),
    ]
