# Generated by Django 5.2 on 2025-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved')], default='sent', max_length=20),
        ),
    ]
