# Generated by Django 5.2 on 2025-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_logbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Lecture Notes', 'Lecture Notes'), ('Samples', 'Samples'), ('Templates', 'Templates'), ('Marking Scheme', 'Marking Scheme')], max_length=20),
        ),
    ]
