# Generated by Django 5.2 on 2025-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mode',
            field=models.CharField(choices=[('development', 'development'), ('research', 'research')], default='development', max_length=20),
        ),
    ]
