# Generated by Django 5.2 on 2025-04-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_mode'),
        ('settings', '0003_alter_documenttheme_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.documentcategories'),
        ),
    ]
