# Generated by Django 5.2 on 2025-04-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_category'),
        ('settings', '0004_documentmodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.documentmodes'),
        ),
    ]
