# Generated by Django 5.2 on 2025-04-20 13:44

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_feedback_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.feedback_upload_path),
        ),
    ]
