# Generated by Django 5.2 on 2025-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_feedback_comment_alter_feedback_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('feedback', 'Feedback')], default='sent', max_length=20),
        ),
    ]
