# Generated by Django 5.2 on 2025-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_logbook_comment_alter_logbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('marking_scheme', 'Marking Scheme'), ('lecture_notes', 'Lecture Notes'), ('samples', 'Samples'), ('templates', 'Templates'), ('forms', 'Forms'), ('other', 'Other')], max_length=255),
        ),
    ]
