# Generated by Django 5.2 on 2025-05-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='course',
            field=models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2')], default='FYP1', max_length=5),
        ),
    ]
