const grading_contents = [
  {
    label: "Supervision",
    marks: 4,
    weightage: 0.1,
    PIC: "supervisor",
    contents: ["Log Book", "Meeting Frequency", "Work Ethic", "Independence"],
  },
  {
    label: "Progress Report 1",
    marks: 4,
    weightage: 0.1,
    PIC: "supervisor",
    contents: [
      "Progress of Chapter 1",
      "Progress of Chapter 2",
      "Writing style, Format and Clarity",
      "Citation and references",
    ],
  },
  {
    label: "Progress Report 2",
    marks: 4,
    weightage: 0.1,
    PIC: "supervisor",
    contents: [
      "Completeness of Chapter 3",
      "Completeness of Chapter 4",
      "Writing style, Format and Clarity",
      "Citation and references",
    ],
  },
  {
    label: "Final Report",
    marks: 4,
    weightage: 0.3,
    PIC: "examiner",
    contents: [
      "Abstract",
      "Completeness of Chapter 1",
      "Completeness of Chapter 2",
      "Completeness of Chapter 3",
      "Completeness of Chapter 4",
      "Writing style, Format and Clarity",
      "Citation and references",
    ],
  },
  {
    label: "Design",
    marks: 4,
    weightage: 0.25,
    PIC: "examiner",
    contents: [
      "System Flow and Architecture",
      "User Requirement",
      "Database Design",
      "UML Design",
      "Gantt Chart",
      "Interface Design",
      "Course Domain Elements",
    ],
  },
  {
    label: "Problem Formulation and Research",
    marks: 4,
    weightage: 0.25,
    PIC: "examiner",
    contents: [
      "Introduction",
      "Research Problems and Research Questions",
      "Problem Background and Objectives",
      "Research Phases",
      "Experiment Design / Research Procedure",
    ],
  },
  {
    label: "Presentation",
    marks: 4,
    weightage: 0.1,
    PIC: "examiner",
    contents: [
      "Appearance and Attitude",
      "Project Understanding / Content",
      "Clarity of Presentation",
      "Question and Answer Session",
    ],
  },
  {
    label: "Ethics",
    marks: 4,
    weightage: 0.05,
    PIC: "coordinator",
    contents: ["Similarity Percentage", "Submission"],
  },
];

export default grading_contents;
