# Generated by Django 5.2 on 2025-04-11 03:32

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_available_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'First Choice'), (2, 'Second Choice'), (3, 'Third Choice')])),
                ('proof', models.FileField(blank=True, help_text='Proof of request (image or PDF)', null=True, upload_to=users.models.upload_to_supervisor_requests)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'priority'],
                'unique_together': {('student', 'priority')},
            },
        ),
    ]
