# Generated by Django 5.2 on 2025-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supervisorsrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorsrequest',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='supervisor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
