# Generated by Django 5.2 on 2025-04-12 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='evaluators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_examiner': True}, related_name='evaluatees', to=settings.AUTH_USER_MODEL),
        ),
    ]
