# Generated by Django 5.2 on 2025-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_evaluators'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mode',
            field=models.CharField(choices=[('Research', 'Research'), ('Development', 'Development')], default='Development', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='mode',
            field=models.CharField(choices=[('Research', 'Research'), ('Development', 'Development')], default='Development', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
