# Generated by Django 5.2 on 2025-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_student_mode_student_topic_supervisorsrequest_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mode',
            field=models.CharField(choices=[('research', 'research'), ('development', 'development')], default='development', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisorsrequest',
            name='mode',
            field=models.CharField(choices=[('research', 'research'), ('development', 'development')], default='development', max_length=20),
        ),
    ]
