# Generated by Django 5.2 on 2025-04-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_mode_alter_supervisorsrequest_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2'), ('Both', 'Both')], default='FYP1', max_length=10)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'course_coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
