# Generated by Django 5.2 on 2025-05-01 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_coursecoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecoordinator',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('role', 'student'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='course_coordinator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
