# Generated by Django 5.2 on 2025-05-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_coursecoordinator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('FYP1', 'FYP1'), ('FYP2', 'FYP2'), ('inactive', 'Inactive')], max_length=10),
        ),
    ]
