# Generated by Django 5.2 on 2025-05-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
    ]
