# Generated by Django 5.2 on 2025-05-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorsrequest',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
