# Generated by Django 5.2 on 2025-05-30 03:30

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_supervisorsrequest_cgpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisorsrequest',
            options={'ordering': ['student']},
        ),
        migrations.AlterUniqueTogether(
            name='supervisorsrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='first_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='first_proof',
            field=models.FileField(blank=True, help_text='Proof of first choice request (image or PDF)', null=True, upload_to=users.models.upload_to_supervisor_requests),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='second_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='second_proof',
            field=models.FileField(blank=True, help_text='Proof of second choice request (image or PDF)', null=True, upload_to=users.models.upload_to_supervisor_requests),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='third_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='third_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsrequest',
            name='third_proof',
            field=models.FileField(blank=True, help_text='Proof of third choice request (image or PDF)', null=True, upload_to=users.models.upload_to_supervisor_requests),
        ),
        migrations.AlterField(
            model_name='supervisorsrequest',
            name='mode',
            field=models.CharField(choices=[('research', 'Research'), ('development', 'Development')], default='development', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisorsrequest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.RemoveField(
            model_name='supervisorsrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='supervisorsrequest',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='supervisorsrequest',
            name='supervisor_id',
        ),
        migrations.RemoveField(
            model_name='supervisorsrequest',
            name='supervisor_name',
        ),
    ]
