# Generated by Django 5.2 on 2025-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='directory',
            field=models.CharField(choices=[('supervisors', 'Supervisors'), ('submissions', 'Submissions'), ('logs', 'Logs'), ('course_outline', 'Course Outline'), ('home', 'Home'), ('documents', 'Documents')], max_length=20),
        ),
    ]
