# Generated by Django 5.2 on 2025-04-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_period_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('src', models.FileField(blank=True, null=True, upload_to='outlines/')),
            ],
        ),
    ]
