# Generated by Django 5.2 on 2025-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('feedback', 'Feedback'), ('completed', 'Completed'), ('closed', 'Closed'), ('missed', 'Missed')], max_length=20)),
            ],
        ),
    ]
