# Generated by Django 5.2 on 2025-04-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_submissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outline',
        ),
    ]
