# Generated by Django 5.2 on 2025-04-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_delete_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='status',
        ),
    ]
