# Generated by Django 5.2 on 2025-04-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_remove_submissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_selection_period',
            field=models.BooleanField(default=False),
        ),
    ]
