# Generated by Django 5.2 on 2025-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_announcement_course_period_course_submissions_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='directory',
            field=models.CharField(blank=True, choices=[('supervisors', 'Supervisors'), ('submissions', 'Submissions'), ('logs', 'Logs'), ('course_outline', 'Course Outline'), ('home', 'Home'), ('documents', 'Documents')], max_length=20, null=True),
        ),
    ]
